### ISSUE TITLE
StudyBuddy runs indefinitely as long as you don't manually stop it, even when the PC is shut down

### ISSUE THREAD

**Issue by dennisorlando** [studybuddydev/studybuddy-app#18]
Hi, I woke up this morning with the studybuddy timer at ~20 hours; I think that "forgetting to close StudyBuddy" is an issue worth addressing.
I'm biased towards creating a desktop app which obviously closes (thus stopping the timer) whenever you shut down your computer; this would also open up a lot of new opportunities in the field of desktop integration, like automatic activity monitoring (like [ActivityWatch](https://github.com/ActivityWatch/activitywatch) does) etc..

**Comment by alessiogandelli** [comment]
yes that's true, if you forget the pause after 15 min it will enter in long break mode, and after the next play it will discard the long one, while for the studying part we were thinking about a Netflix style message  "are you still studying?" if no user is detected.  still have to figure out how to say that a user abandoned a pomodoro

**Comment by dennisorlando** [comment]
A potential solution would be to let the user choose between multiple "abandonment behaviors". 
This way we can implement multiple heuristics / algorithms and not really care whether or not it's the best solution, like:
- ignore (don't stop pomodoro, not even if it has been running since 1999)
- stop on browser exit
- "are you still there?" popup after x minutes; (maybe the user can configure the amount of minutes before the popup?)
- "void if abandoned" checkbox, which deletes a pomodoro if it's considered "abandoned"

**Comment by gabrielesalvi** [comment]
The issue is solved with the last update. 

We went for the "are you still there?" option, with a popup after a certain inactivity period.
