### ISSUE TITLE
There are 1500 repositories named "StudyBuddy"

### ISSUE THREAD

**Issue by dennisorlando** [studybuddydev/studybuddy-app#19]
Hi,
there are tons of discoverable projects, sites and repos named "studybuddy", which makes this app difficult to find and definitely not distinct enough. 
I was wondering if there's any solution to this issue or if this project should just stick with the problem.

**Comment by alessiogandelli** [comment]
up to now being noticed on github is not on our todolist, maybe this will be an issue in the future
